// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'ocean', 'sunset', 'forest', 'high-contrast', 'cocoa-ember', 'aurora', 'arctic', 'ember', 'earthy-rhythm', 'luxury-ember', 'midnight-moss', 'deep-amethyst', 'obsidian-gold', 'slate-crimson', 'basalt-cyan', 'charcoal-rose', 'forest-rust', 'abyss-electric', 'ink-bronze', 'carbon-mint', 'velvet-noir', 'sapphire-luxury', 'champagne-noir', 'platinum-edge', 'graphite-amber', 'burgundy-depths', 'imperial-plum', 'espresso-gold', 'titanium-indigo', 'onyx-coral']
    }
}

export {}
