export const themes = [
    { name: "light", label: "Light", icon: "☀️" },
    { name: "dark", label: "Dark", icon: "🌙" },
    { name: "ocean", label: "Ocean", icon: "🌊" },
    { name: "sunset", label: "Sunset", icon: "🌅" },
    { name: "forest", label: "Forest", icon: "🌲" },
    { name: "high-contrast", label: "High Contrast", icon: "♿" },
    { name: "cocoa-ember", label: "Cocoa Ember", icon: "🍫" },
    { name: "aurora", label: "Aurora", icon: "🌌" },
    { name: "arctic", label: "Arctic", icon: "🧊" },
    { name: "ember", label: "Ember", icon: "🌋" },
    { name: "earthy-rhythm", label: "Earthy Rhythm", icon: "🥁" },
    { name: "luxury-ember", label: "Luxury Ember", icon: "🔥" },
    { name: "midnight-moss", label: "Midnight Moss", icon: "🌲" },
    { name: "deep-amethyst", label: "Deep Amethyst", icon: "🔮" },
    { name: "obsidian-gold", label: "Obsidian Gold", icon: "🪙" },
    { name: "slate-crimson", label: "Slate Crimson", icon: "🩸" },
    { name: "basalt-cyan", label: "Basalt Cyan", icon: "💎" },
    { name: "charcoal-rose", label: "Charcoal Rose", icon: "🌹" },
    { name: "forest-rust", label: "Forest Rust", icon: "🍂" },
    { name: "abyss-electric", label: "Abyss Electric", icon: "⚡" },
    { name: "ink-bronze", label: "Ink Bronze", icon: "🏺" },
    { name: "carbon-mint", label: "Carbon Mint", icon: "🌿" }
];
