export const third_bca = [
  "Fathima Sehva OP",
  "Nihala Sherin",
  "Abhay PM",
  "Abhinav Krishna k",
  "Abin Gopu",
  "Adithyan N",
  "Alok S",
  "Amal K Gopi",
  "Arijith M",
  "Muhammad Ajmal TP",
  "Muhammad Hadi CK",
  "Muhammad Nihal",
  "Sathpriyan T",
  "Shahin Arif PP",
  "Adithya PK",
  "Anshya R",
  "Avya KP",
  "Jyothi Lakshmi",
  "Silpa K Joy",
  "Sravya PV",
  "Tara Muhendra",
  "Abhinav Pavithran",
  "Abhram UK",
  "Adhil Javid",
  "Adwaith Anand SR",
  "Anukiran",
  "Asmul Hisham",
  "Deslin MJ",
  "Goutham Sabu",
  "Jasim Jaleel Moosa",
  "Muhammad Fasal",
  "Muhammad Sinan",
  "Sharon K Joy",
  "Sreeraj p",
  "Rhema Jarish"
];
